### PR TITLE
feat: write csv to temp file rather than in memory

### PR DESCRIPTION
**Pull request by nick-solly**
### Test File

[main.py](https://github.com/QuickRelease/django-async-downloads/files/7817802/main.txt)

### Test Results

```
SMALL TESTS

Filename: C:/Users/NickSolly/Django/howtosave/main.py

Line #    Mem usage    Increment  Occurrences   Line Contents
=============================================================
    67     18.8 MiB     18.8 MiB           1       @profile
    68                                             def run_in_memory(self):
    69     18.8 MiB      0.0 MiB           1           output = StringIO(newline="")
    70     18.8 MiB      0.0 MiB           1           writer = csv.writer(output, lineterminator="\n")
    71     19.7 MiB      0.6 MiB        1001           for row in self.data_generator():
    72     19.7 MiB      0.2 MiB        1000               writer.writerow(row)
    73     19.8 MiB      0.1 MiB           1           self.default_storage.save("output_memory.csv", ContentFile(output.getvalue().encode()))

run_in_memory took 3.1323466 seconds


Filename: C:/Users/NickSolly/Django/howtosave/main.py

Line #    Mem usage    Increment  Occurrences   Line Contents
=============================================================
    59     19.0 MiB     19.0 MiB           1       @profile
    60                                             def run_with_save(self):
    61     19.1 MiB      0.0 MiB           1           with tempfile.NamedTemporaryFile(mode='r+', newline="") as temp_file:
    62     19.1 MiB      0.0 MiB           1               writer = csv.writer(temp_file, lineterminator="\n")
    63     19.1 MiB      0.0 MiB        1001               for row in self.data_generator():
    64     19.1 MiB      0.0 MiB        1000                   writer.writerow(row)
    65     19.2 MiB      0.2 MiB           1               self.default_storage.save("output_save.csv", temp_file)


run_with_save took 3.0361296999999996 seconds



LARGE TESTS

Filename: C:/Users/NickSolly/Django/howtosave/main.py

Line #    Mem usage    Increment  Occurrences   Line Contents
=============================================================
    67     19.1 MiB     19.1 MiB           1       @profile
    68                                             def run_in_memory(self):
    69     19.1 MiB      0.0 MiB           1           output = StringIO(newline="")
    70     19.1 MiB      0.0 MiB           1           writer = csv.writer(output, lineterminator="\n")
    71    100.0 MiB     38.5 MiB      100001           for row in self.data_generator():
    72    100.0 MiB      7.2 MiB      100000               writer.writerow(row)
    73     93.9 MiB     -6.1 MiB           1           self.default_storage.save("output_memory.csv", ContentFile(output.getvalue().encode()))


run_in_memory took 300.4951648 seconds

Filename: C:/Users/NickSolly/Django/howtosave/main.py

Line #    Mem usage    Increment  Occurrences   Line Contents
=============================================================
    59     19.0 MiB     19.0 MiB           1       @profile
    60                                             def run_with_save(self):
    61     19.0 MiB      0.0 MiB           1           with tempfile.NamedTemporaryFile(mode='r+', newline="") as temp_file:
    62     19.0 MiB      0.0 MiB           1               writer = csv.writer(temp_file, lineterminator="\n")
    63     19.0 MiB  -3124.5 MiB      100001               for row in self.data_generator():
    64     19.0 MiB  -3124.5 MiB      100000                   writer.writerow(row)
    65     19.1 MiB      0.1 MiB           1               self.default_storage.save("output_save.csv", temp_file)


run_with_save took 303.7850775 seconds
```

### CODE REVIEW

**Comment by nick-solly** [comment]
@dave-v - want to discuss this with you.  Came out of memory issues @davidfoleyQR was having with some large exports on TheHub.

**Comment by dave-v** [comment]
> @dave-v - want to discuss this with you. Came out of memory issues @davidfoleyQR was having with some large exports on TheHub.

Seems surprising that the timing is so similar. There is also [SpooledTemporaryFile](https://docs.python.org/3/library/tempfile.html#tempfile.SpooledTemporaryFile) which is in-memory until some maximum size, after which it saves to a temporary file.

**Comment by nick-solly** [comment]
Tests with `SpooledTemporaryFile`:

[main.py](https://github.com/QuickRelease/django-async-downloads/files/7847100/main.txt)

```

SMALL TESTS
Filename: C:/Users/NickSolly/Django/howtosave/main.py

Line #    Mem usage    Increment  Occurrences   Line Contents
=============================================================
    68     18.8 MiB     18.8 MiB           1       @profile
    69                                             def run_in_memory(self):
    70     18.8 MiB      0.0 MiB           1           output = StringIO(newline="")
    71     18.8 MiB      0.0 MiB           1           writer = csv.writer(output, lineterminator="\n")
    72     19.8 MiB      0.7 MiB        1001           for row in self.data_generator():
    73     19.8 MiB      0.3 MiB        1000               writer.writerow(row)
    74     20.0 MiB      0.3 MiB           1           self.default_storage.save("output_memory.csv", ContentFile(output.getvalue().encode()))


run_in_memory took 3.3960106000000003 seconds

<class '_io.TextIOWrapper'>
Filename: C:/Users/NickSolly/Django/howtosave/main.py

Line #    Mem usage    Increment  Occurrences   Line Contents
=============================================================
    59     19.1 MiB     19.1 MiB           1       @profile
    60                                             def run_with_save(self):
    61     19.1 MiB      0.0 MiB           1           with tempfile.SpooledTemporaryFile(max_size=5 * 1e6, mode='r+', newline="") as temp_file:
    62     19.1 MiB      0.0 MiB           1               writer = csv.writer(temp_file, lineterminator="\n")
    63     20.7 MiB    -98.8 MiB        1001               for row in self.data_generator():
    64     20.7 MiB    -97.2 MiB        1000                   writer.writerow(row)
    65     20.5 MiB     -0.2 MiB           1               print(type(temp_file._file))
    66     19.1 MiB     -1.4 MiB           1               self.default_storage.save("output_save.csv", temp_file)


run_with_save took 3.0767171 seconds


LARGE TESTS
Filename: C:/Users/NickSolly/Django/howtosave/main.py

Line #    Mem usage    Increment  Occurrences   Line Contents
=============================================================
    68     19.1 MiB     19.1 MiB           1       @profile
    69                                             def run_in_memory(self):
    70     19.1 MiB      0.0 MiB           1           output = StringIO(newline="")
    71     19.1 MiB      0.0 MiB           1           writer = csv.writer(output, lineterminator="\n")
    72     99.8 MiB     14.5 MiB      100001           for row in self.data_generator():
    73     99.8 MiB    -16.5 MiB      100000               writer.writerow(row)
    74     93.6 MiB     -6.2 MiB           1           self.default_storage.save("output_memory.csv", ContentFile(output.getvalue().encode()))


run_in_memory took 306.4694564 seconds

<class 'tempfile._TemporaryFileWrapper'>
Filename: C:/Users/NickSolly/Django/howtosave/main.py

Line #    Mem usage    Increment  Occurrences   Line Contents
=============================================================
    59     19.2 MiB     19.2 MiB           1       @profile
    60                                             def run_with_save(self):
    61     19.2 MiB      0.0 MiB           1           with tempfile.SpooledTemporaryFile(max_size=5 * 1e6, mode='r+', newline="") as temp_file:
    62     19.2 MiB      0.0 MiB           1               writer = csv.writer(temp_file, lineterminator="\n")
    63     25.5 MiB -584467.0 MiB      100001               for row in self.data_generator():
    64     25.5 MiB -584460.8 MiB      100000                   writer.writerow(row)
    65     19.2 MiB     -6.2 MiB           1               print(type(temp_file._file))
    66     19.4 MiB      0.2 MiB           1               self.default_storage.save("output_save.csv", temp_file)


run_with_save took 312.2572629 seconds


Process finished with exit code 0
```

**Review by davidfoleyQR — APPROVED** [review]
`SpooledTemporaryFile` is really cool.  Just looked up the documentation.  Ill leave it to you to merge if you'd like another approval, but seems like a really smart way of doing this

**Pull request merged**
